# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{couchlogic}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mauricio Gomes"]
  s.date = %q{2010-10-11}
  s.description = %q{An advanced Ruby interface for CouchDB.}
  s.email = %q{mgomes@geminisbs.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "VERSION",
     "lib/couchlogic.rb",
     "lib/couchlogic/client/client.rb",
     "lib/couchlogic/client/connection.rb",
     "lib/couchlogic/client/endpoint.rb",
     "lib/couchlogic/client/response.rb",
     "lib/couchlogic/errors.rb"
  ]
  s.homepage = %q{http://github.com/mgomes/couchlogic}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{An advanced Ruby interface for CouchDB}
  s.test_files = [
    "spec/couchlogic_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<yajl-ruby>, ["~> 0.7.8"])
      s.add_runtime_dependency(%q<curb>, ["~> 0.7.8"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<yajl-ruby>, ["~> 0.7.8"])
      s.add_dependency(%q<curb>, ["~> 0.7.8"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<yajl-ruby>, ["~> 0.7.8"])
    s.add_dependency(%q<curb>, ["~> 0.7.8"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

